Hw02 draft
nite4g/otus-go-homework pull request #2
Opened 2020-12-21 17:36 UTC by nite4g

2020-12-31 10:51 UTC, kulti requested changes
Решение не соответствует заданию:
1. Зачем-то фильтруются пробелы.
2. Экранирование тоже сделано не так, как описано в задании.

Есть предложение — сдать решение для задания без звездочки, а звездочку уже решать потом по желанию (я помогу с ним).

2020-12-31 10:51 UTC, kulti commented on hw02_unpack_string/unpack_test.go
>  			expected: `qwe\3`,
Это странное изменение:
1. Код перестал быть отформатированным (странно, что линтер не упал).
2. Не понятно, почему появился таб (и почему его нет в ожидаемом значении). Если это какой-то новый тест, то давайте его отдельно добавим.

2020-12-31 10:51 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			expected: `gfgr3`,
Думаю, решение неверное, т.к. оно отфильтровывает пробелы. Чуть ниже есть не менее странный тест на `\ 3фыва` — его логику я вообще сначала не понял, т.к. в задании четко сказано:
> заэкранировать можно только цифру или слэш.

А тут экранируется пробел. Почитав код, понял, что в решении зачем-то фильтруются пробелы. Откуда взялось это требование?

2020-12-31 10:51 UTC, kulti commented on hw02_unpack_string/unpack.go
> +var state string = `default`
Для лучшей читаемости кода и уменьшения способов отстрелить себе ногу для стейта лучше завести тип и константы:
```
type state string

const (
    defaultState state = "default"
    slashedState state = "slashed"
    ...
)

2020-12-31 10:51 UTC, kulti commented on hw02_unpack_string/unpack.go
> +var wasDigit bool // just to control pair digit in the raw
Почему эта переменная глобальная? Лучше не использовать глобальные переменны, т.к. это может влиять на тесты.

2021-01-09 13:50 UTC, nite4g commented on hw02_unpack_string/unpack_test.go
>  			expected: `qwe\3`,
Это случайно пролезло,  в какой то момент видимо запихал пробел , скорее всего жертва копипасты и моей невнимательности.

2021-01-09 13:50 UTC, nite4g commented on hw02_unpack_string/unpack_test.go
> +			expected: `gfgr3`,
Это следствие ошибки выше,  сначала был сделана ошибка в тесте, а потом появилась мысль что неплохо бы убрать все whitespaces.   В целом безобидное дополнение. Не так нет, "зачистил" весь whitespase-clean.

2021-01-09 13:51 UTC, nite4g commented on hw02_unpack_string/unpack.go
> +var state string = `default`
я,  к сожалению, не могу понять какая такая конструкция может применятся в switch условии.

2021-01-09 13:51 UTC, nite4g commented on hw02_unpack_string/unpack.go
> +var wasDigit bool // just to control pair digit in the raw
это было к сожалению вынужденная  и осознанная мера, нужно было уменьшить количество строк в функции что бы линтер не ругался.  Сделал локальными.

2021-01-10 06:16 UTC, kulti commented on hw02_unpack_string/unpack.go
> +var state string = `default`
Суть в том, что в переменной `state` хранится строка. Нужно, чтобы во всех местах эти строки были написаны без опечаток. Такой код сложнее поддерживать и изменять, т.к. допустить опечатку легко. Если вынести строки в константы, то ошибку допустить станет сложнее.

В вашем случае это выглядело бы так:
```
func Unpack(...) {
	...
	state := defaultState
	...
	for _, char := range compStr {
		switch state {
		case defaultState:
			...
		case slashedState:
			...
		...
		}
	}
	...

```

2021-01-10 06:28 UTC, kulti commented on hw02_unpack_string/unpack.go
> +var wasDigit bool // just to control pair digit in the raw
Линтеры не ругаются.

Они говорят что-то вроде "я тут посчитал количество строк в функции, как-то их много — возможно, функция получилась сложной для понимания". И задача в этом случае не уменьшить число строк, а понять, правда ли из-за длинны функция получилась сложная (например, из-за большой вложенности if, for, switch или из-за смешивания разных уровней абстракций). Почему тот или иной линтер считает, что что-то не в порядке, надо читать в их документации. Там часто есть примеры, как исправить типичные ошибки. Ссылки на все линтеры есть [тут](https://golangci-lint.run/usage/linters).

Если линтер прав в своих предположения, то надо фиксить. В случае с funlen обычно выделяют новые функции на других уровнях абстракции.

Если же все в порядке (например, создание очереди к rabbitmq может быть довольно большим по количеству строк, но там простой прямолинейный код), то это называется [false positive](https://golangci-lint.run/usage/false-positives). Нужно отключить линтер с поясняющий комментарием. Для примера с rabbitmq: "//nolint:funlen // because of simple rabbitmq setup".

2021-01-10 06:34 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			expected: `gfgr3`,
Хорошо. Можно зачистку от пробелов добавить. Только стоит сообщать, что вы немного по другому задание сделали. Иначе выглядит так, что не поняли и сделали что-то другое.

Неплохо бы, чтобы в подобных изменениях условий ДЗ был смысл. Сейчас это звучит так:
- написан неправильный тест;
- сделан неправильный код, чтобы пройти неправильный тест.

2021-01-10 06:38 UTC, kulti requested changes
Решение все еще не соответствует заданию. Про фильтрацию пробелов разобрались. Осталось решить, что делать с экранированием.

Я попробую еще раз предложить сдать решение для задания без звездочки, а звездочку уже решать потом по желанию (я помогу с ним).

2021-01-10 06:38 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			expected: `dfe\n`,
Повторюсь, что экранирование сделано не так, как описано в задании. Экранироваться могут только цифры и слэши. В этом тесте экранируется символ n, а в конце вообще незакрытое экранирование. Это невалидная строка сразу по двум критериям.

2021-01-10 06:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +var state string = `default`
И еще один момент — у `switch` нет ветки `default`, т.е. какие-то символы могут вообще пройти мимо обработки.

2021-01-10 09:07 UTC, nite4g commented on hw02_unpack_string/unpack_test.go
> +			expected: `dfe\n`,
со слешом в конце понятно, но в основном условии задачи есть "d\n5abc" => "d\n\n\n\n\nabc" , что вполне логично интерпретировано мной как то, что для "\n" - перенос строки подчиняется правилам распаковки без именений, как в тесте ниже:
input:    `f\n2xr`,
expected: `f\n\nxr`,

2021-01-10 12:54 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			expected: `dfe\n`,
Артем, в условии ДЗ написано:
> Как видно из примера, заэкранировать можно только цифру или слэш.

Если есть сомнения по поводу правильности формулировки задания — лучше уточнить. Иногда мы ошибаемся, иногда формулируем так, что можно понять по разному. Мы такое исправляем, чтобы следующим студентам было проще. Предлагаю в следующий раз сразу приходить в общий чат или в личку в слаке, чтобы разобраться, что именно нужно и что вызывает сомнения.

В данном случае формулировка верная. Дело в кавычках. "\n" — это символ переноса строки. \`\n\` — это два символа `\` и `n`. Строка в двойных кавычках интерпретирует эскейп-последовательности. Строка в косых кавычка этого не делает (своего рода сырая "raw" строка).

2021-01-10 16:51 UTC, nite4g commented on hw02_unpack_string/unpack_test.go
> +			expected: `dfe\n`,
Я понял, искусственно усложнил себе задачу.  Поправил.

2021-01-10 16:52 UTC, nite4g commented on hw02_unpack_string/unpack.go
> +var state string = `default`
default добавил

2021-01-11 16:40 UTC, kulti requested changes
Решение пока еще не работает так, как должно.

2021-01-11 16:40 UTC, kulti commented on hw02_unpack_string/unpack_test.go
> +			expected: `aaaabccdddddea`,
В этом тесте экранируется символ a. А должны экранироваться только числа и \. Значит в решении есть ошибка.

2021-01-11 16:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			log.Fatal("Undefined state.")
Лучше бы, конечно, сделать решение, которое не будет паниковать. Но думаю, это лучше в другой раз уже постараться — сейчас важно довести его до рабочего состояния.

2021-01-11 16:40 UTC, kulti commented on hw02_unpack_string/unpack.go
> +				return "", ErrInvalidString
Очень странный "особый" случай. Почему проверка экранирования косой квычки выделена особо?

2021-01-11 17:14 UTC, nite4g commented on hw02_unpack_string/unpack.go
> +			log.Fatal("Undefined state.")
Я поправил, но на мой взгляд логично выбросить ошибку в ситуации когда внезапно возник стейт не предусмотренный логикой.

2021-01-11 17:16 UTC, nite4g commented on hw02_unpack_string/unpack.go
> +				return "", ErrInvalidString
Личная неприязнь к косой кавычке :).  Исправил так что бы более соответствовало условию задачи.

2021-01-11 17:18 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			log.Fatal("Undefined state.")
Это правильное рассуждение. Только тут не ошибка, а паника. Паника — это когда произошло что-то, что происходить не должно. В вашем случае паника тут самое то.

С другой стороны писать код, который может паниковать — так себе идея. Тут нужно полностью переосмысливать и переписывать решение. Поэтому и предлагаю сосредоточиться на том, чтобы оно в первую очередь работало.

2021-01-11 17:22 UTC, kulti approved these changes
Теперь решение должно работать. Получилось запутанно и неаккуратно. В следующем ДЗ можно попробовать сделать чуть лучше.

ДЗ принято на 7 из 10.

Также рекомендую посмотреть разбор этого ДЗ — https://youtu.be/Ow5eCEtQUts.

2021-01-11 17:37 UTC, merged