Hw05 parallel execution
nite4g/otus-go-homework pull request #5
Opened 2021-03-05 18:13 UTC by nite4g

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-03-10 18:48 UTC, balabanovds requested changes
В целом неплохо.
Есть вопросы

2021-03-10 18:48 UTC, balabanovds commented on hw05_parallel_execution/run.go
> +		case t := <-ch:
тут бы еще проверить, что читаем не с закрытого канала...

2021-03-10 18:48 UTC, balabanovds commented on hw05_parallel_execution/run.go
> +			e := t()
а зачем вызывать функцию до проверки на количество ошибок?

2021-03-10 18:48 UTC, balabanovds commented on hw05_parallel_execution/run.go
> +				time.Sleep(time.Millisecond * time.Duration(rand.Intn(50))) //nolint:gosec
еще раз объясните пожалуйста, зачем тут рандомный Sleep?

2021-03-11 17:14 UTC, nite4g commented on hw05_parallel_execution/run.go
> +		case t := <-ch:
проверяем ниже.

2021-03-11 17:17 UTC, nite4g commented on hw05_parallel_execution/run.go
> +			e := t()
нууу, может быть это плохой паттерн, но логика следующая, в реальной жизни мы все таки функцию  вызвали бы , закрытый канал вернет nil,  чуть ниже есть проверка что если не nil, то увеличиваем счетчик ошибок. Правда пока писал подумал что функция тоже может вернуть nil,  а не ошибку как ожидается в условии.

2021-03-11 17:18 UTC, nite4g commented on hw05_parallel_execution/run.go
> +				time.Sleep(time.Millisecond * time.Duration(rand.Intn(50))) //nolint:gosec
В условии задачи сказано что функции могут работать разное время,  sleep в целом именно для этого, других задач он не решает, просто добавляет рандомизацию работы горутин.

2021-03-13 18:07 UTC, nite4g commented on hw05_parallel_execution/run.go
> +		case t := <-ch:
добавил проверку

2021-03-13 18:07 UTC, nite4g commented on hw05_parallel_execution/run.go
> +				time.Sleep(time.Millisecond * time.Duration(rand.Intn(50))) //nolint:gosec
а это убрал.

2021-03-13 18:07 UTC, nite4g commented on hw05_parallel_execution/run.go
> +			e := t()
исправил

2021-03-18 05:11 UTC, balabanovds approved these changes
Спасибо, все вопросы решились
10/10

2021-03-18 20:52 UTC, merged